<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '16',
    'typeid' => '0',
    'title' => 'si设计包括哪些',
    'style' => '',
    'thumb' => 'http://www.miaoyan.com/uploadfile/2019/0718/20190718024553836.jpeg',
    'keywords' => 'si设计',
    'description' => 'si设计包括哪些内容？为什么说SI设计对连锁品牌十分重要？下面花生设计给大家解决一下这些疑问，SI设计可以说是VI的延伸设计，主要体现在品   ',
    'posids' => '1',
    'url' => 'http://www.miaoyan.com/planing/si/1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'miaoyanch888',
    'inputtime' => '1563432262',
    'updatetime' => '1564388923',
    'hitsid' => 'c-1-1',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '4',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '16',
    'typeid' => '0',
    'title' => '广州SI系统设计对连锁品牌的意义 ',
    'style' => '',
    'thumb' => 'http://www.miaoyan.com/uploadfile/2019/0718/20190718024741260.jpeg',
    'keywords' => 'si设计',
    'description' => '一个品牌的成长需要多方面的考虑，必须建立一套完整的VI系统，特别是针对有实体店面销售的品牌，SI系统, 品牌终端店面形象系统的建立必不   ',
    'posids' => '1',
    'url' => 'http://www.miaoyan.com/planing/si/2.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'miaoyanch888',
    'inputtime' => '1563432398',
    'updatetime' => '1563432460',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>